### ISSUE TITLE
Destroy doesn't actually destroy the slider?

### ISSUE THREAD

**Issue by MaxFanov** [mystroken/cachu-slider#7]
I'm using your slider and I have matchMedia with an event listener, if it matches I want to destroy the slider but the destroy() function seems to do nothing at all

**Comment by mystroken** [comment]
Hello Maxim
Thanks for giving a try to the project 🙂
I will try to look at the concern in a short time!

**Comment by mystroken** [comment]
Hello Maxim
I've been looking around the source code... but still no way to reproduce the issue you've described.
Any chance, you share a bit of your code here?

Regards,

**Comment by MaxFanov** [comment]
> Hello Maxim I've been looking around the source code... but still no way to reproduce the issue you've described. Any chance, you share a bit of your code here?
> 
> Regards,

Hey mystroken,
Thanks for the reply, currently I can't really reproduce it either, if it will be a reoccurring problem I'll try to replicate it on a clean JavaScript repository and I'll open a new issue.

**Comment by mystroken** [comment]
Thanks!
I'll be glad to help at that moment.
